//! Installation artifacts: the canonical AGENTS.md block, the Claude Code /
//! Codex hooks JSON, and the response shapes for the four tools that hand
//! these out (`setup`, `sync_agents_block`, `install_hooks`,
//! `connect_agents`).
//!
//! None of these functions edit a file themselves — same as the Python
//! side. They compute artifacts and (for the tool-response functions) touch
//! the store for the minted credential, the setup ticker, and the ledger
//! row; the caller applies the returned content so the change lands in the
//! *agent's own* diff, not a silent server-side write.
//!
//! ## Byte-for-byte requirements
//!
//! The protocol block text (`_BLOCK_BODY`/`block_body`/`canonical_block`)
//! and the hook shell-command strings are written into a developer's
//! `AGENTS.md`, `.claude/settings.json`, and `.codex/hooks.json`. A
//! reworded byte here is a version bump every client has to re-sync, so
//! this module never retypes that text — it is extracted verbatim from the
//! Python source (`collide/blocks.py`) into sibling `.txt` files and pulled
//! in with `include_str!`:
//!   - `block_body.txt` — the template, `{{`/`}}` already unescaped to
//!     single braces, `{version}`/`{repo_id}` left as literal tokens this
//!     module substitutes at call time.
//!   - `hook_report_command.txt`, `hook_gate_command.txt`,
//!     `hook_bootstrap_command.txt`, `hook_precommit_shim.txt` — these are
//!     module-level constants in Python (computed once from OTHER
//!     constants, never from a function argument), so their resolved text
//!     is stable and is embedded as-is rather than rebuilt at runtime.
//!   - `hook_native_install_template.txt` — same story, `__BASE__` swapped
//!     in by `native_hook_install_script`.
//!
//! Everything that genuinely depends on a call argument (`hooks_json`,
//! `codex_hooks_json`, `collide_config_json`, `mcp_json`, the `*_hook_command`
//! builders that take a hook file / fallback / propagate flag) is real
//! translated logic, checked against a golden dump of the Python output in
//! the `tests` module below (`blocks_golden.json`, generated by running the
//! Python functions with the same inputs).
//!
//! ## Scope boundary
//!
//! `setup_tool_response` / `install_hooks_response` / `connect_agents_response`
//! take an already-resolved [`ArtifactRequest`] rather than an `auth`/`ctx`
//! object: workspace routing (`workspace_for`), scope resolution
//! (`scope_of`), and the read-only access check are the MCP dispatch
//! layer's job (same division every other ported module — `intents.rs`,
//! `report.rs` — already uses). This module mints the hook credential
//! itself (a direct `TOKEN_BUCKET` write, record-compatible with
//! `auth::principal_for_bearer`) since that is inseparable from "what
//! `setup` returns", but it does not resolve identity or workspace.

use serde_json::{json, Map, Value};

use crate::store::{now, Store};

// ------------------------------------------------------------- versioning

// Kept in `envelope.rs` (it already rides these on every `/report`); reused
// here rather than redeclared so the two halves cannot drift apart.
pub use crate::envelope::BLOCK_VERSION;
#[cfg(test)]
use crate::envelope::HOOK_ARTIFACT_VERSION;

pub const START_MARKER: &str = "<!-- collide:start -->";
pub const END_MARKER: &str = "<!-- collide:end -->";

// ---------------------------------------------------------- the block text

/// The un-rendered template: Python's `_BLOCK_BODY` with its doubled
/// `{{`/`}}` (literal-brace escapes for `.format()`) already resolved to
/// single braces, and `{version}` / `{repo_id}` left as the two literal
/// tokens this module substitutes. See the module doc for how this file
/// was produced.
const BLOCK_BODY_TEMPLATE: &str = include_str!("block_body.txt");

/// Python's `blocks.block_body(repo_id)`.
pub fn block_body(repo_id: &str) -> String {
    BLOCK_BODY_TEMPLATE
        .replace("{version}", &BLOCK_VERSION.to_string())
        .replace("{repo_id}", repo_id)
}

/// The block version an AGENTS.md file ACTUALLY carries, or `None` when the
/// file has no Collide block. Ground truth for the setup ticker — see
/// `envelope::reconcile_setup_version`, which this feeds.
pub fn parse_block_version(content: &str) -> Option<i64> {
    let start = content.find(START_MARKER)?;
    let body = match content[start + START_MARKER.len()..].find(END_MARKER) {
        Some(rel_end) => &content[start..start + START_MARKER.len() + rel_end],
        None => &content[start..],
    };
    let needle = "cross-agent collision awareness (v";
    let digits_start = body.find(needle)? + needle.len();
    let rest = &body[digits_start..];
    let end = rest.find(')')?;
    let digits = &rest[..end];
    if digits.is_empty() || !digits.bytes().all(|b| b.is_ascii_digit()) {
        return None;
    }
    digits.parse().ok()
}

pub fn canonical_block(repo_id: &str) -> String {
    format!("{START_MARKER}\n{}\n{END_MARKER}", block_body(repo_id))
}

/// The mandatory protocol written into every agent's native rules file.
/// Shared files (AGENTS.md, windsurf/copilot) carry the marker-wrapped
/// block so re-syncing never clobbers a teammate's own instructions;
/// dedicated files are self-contained.
pub fn agent_rules_files(repo_id: &str) -> Value {
    let body = block_body(repo_id);
    let block = canonical_block(repo_id);
    let cursor_mdc = format!(
        "---\ndescription: Collide cross-agent collision protocol (required)\nalwaysApply: true\n---\n\n{body}\n"
    );
    let clinerules = format!("{body}\n");
    let mut map = Map::new();
    map.insert("AGENTS.md".into(), json!(block));
    map.insert(".cursor/rules/collide.mdc".into(), json!(cursor_mdc));
    map.insert(".clinerules/collide.md".into(), json!(clinerules));
    map.insert(".windsurfrules".into(), json!(block));
    map.insert(".github/copilot-instructions.md".into(), json!(block));
    Value::Object(map)
}

/// The URL agents connect to. Canonical when the server names one
/// (COLLIDE_MCP_URL); else the classic `{server}/mcp`; else a placeholder.
pub fn mcp_endpoint(server_url: &str, mcp_url: &str) -> String {
    if !mcp_url.is_empty() {
        return mcp_url.trim_end_matches('/').to_string();
    }
    if server_url.is_empty() {
        "https://<collide-server>/mcp".to_string()
    } else {
        format!("{}/mcp", server_url.trim_end_matches('/'))
    }
}

/// Repo-committable MCP configs so each client discovers the server.
pub fn agent_mcp_files(server_url: &str, mcp_url: &str) -> Value {
    let cfg = dumps_with_newline(&mcp_json(server_url, mcp_url));
    json!({".mcp.json": cfg.clone(), ".cursor/mcp.json": cfg})
}

/// Config that lives outside the repo (user-global) or is a shell command,
/// returned as copy-paste snippets rather than committable files.
pub fn agent_snippets(server_url: &str, repo_id: &str, mcp_url: &str) -> Value {
    let url = mcp_endpoint(server_url, mcp_url);
    let stripped = server_url.trim_end_matches('/');
    let srv = if stripped.is_empty() { "https://<collide-server>" } else { stripped };
    let codex = format!(
        "Codex reads AGENTS.md for the protocol and .codex/hooks.json for the report+gate hooks \
(committed by connect_agents), so it gets real per-edit blocking, not just advisory. Approve the \
hooks once when Codex prompts for trust (or set bypass_hook_trust). Codex pins that trust to a \
hash of the hook definition and does not reload it mid-session, so after Collide writes the file, \
restart Codex and approve it in /hooks. For the MCP tools, add to ~/.codex/config.toml:\n\
[mcp_servers.collide]\nurl = \"{url}\"\n"
    );
    let cursor = format!(
        "Cursor reads .cursor/rules/collide.mdc for the protocol and .cursor/hooks.json for the \
report+gate hooks (both committed by connect_agents), so it gets real per-edit blocking too. Its \
preToolUse answer carries allow/deny/ask, and its postToolUse carries the briefing notes back into \
the agent. There is no batch event, so the repo's own check is spawned after a write and its \
verdict rides the next tool result. MCP tools come from the committed .cursor/mcp.json: \
{{\"mcpServers\": {{\"collide\": {{\"type\": \"http\", \"url\": \"{url}\"}}}}}}\n"
    );
    let hermes = format!(
        "Hermes runs Collide's committed hooks through its plugin hooks. Add to ~/.hermes/config.yaml:\nhooks:\n  pre_llm_call: [\"python3 .collide/report_hook.py --harness hermes\"]\n  pre_tool_call: [\"python3 .collide/gate_hook.py --harness hermes\"]\n  post_tool_call: [\"python3 .collide/report_hook.py --harness hermes\"]\nGating and reporting both work. Hermes discards a post_tool_call return value by design, so notes \
that would ride a tool result are queued and arrive with the next turn's briefing instead. MCP \
tools: {{\"mcpServers\": {{\"collide\": {{\"type\": \"http\", \"url\": \"{url}\"}}}}}}\n"
    );
    let cline_windsurf = format!(
        "Add the server to your Cline/Windsurf MCP settings (VS Code):\n\
{{\"mcpServers\": {{\"collide\": {{\"type\": \"http\", \"url\": \"{url}\"}}}}}}\n"
    );
    let watcher = format!(
        "Enforcement floor for ANY agent — reports every edit from disk, no hooks needed:\n\
pipx install collide-watch   # or: pip install collide-watch\n\
collide-watch --repo-id \"{repo_id}\" --server \"{srv}\" --token \"$COLLIDE_TOKEN\"\n"
    );
    json!({"codex": codex, "cursor": cursor, "hermes": hermes, "cline_windsurf": cline_windsurf, "watcher": watcher})
}

// ------------------------------------------------------------- file paths

pub const HOOK_FILE: &str = ".collide/report_hook.py";
pub const GATE_HOOK_FILE: &str = ".collide/gate_hook.py";
/// per-harness hook configs: same committed scripts, each harness's own file
pub const CODEX_HOOKS_FILE: &str = ".codex/hooks.json";
pub const CURSOR_HOOKS_FILE: &str = ".cursor/hooks.json";
pub const PRECOMMIT_SCRIPT_FILE: &str = ".collide/pre_commit.py";
pub const NATIVE_INSTALL_FILE: &str = ".collide/install-native-hook.sh";
/// The native hook, pinned and committed — see [`hooks_lock`].
pub const HOOKS_LOCK_FILE: &str = ".collide/hooks.lock";
/// CI's Ed25519 release-signing key, public half (the hooks carry the same).
pub const HOOK_SIGNING_KEY: &str = "17092e6d5632783f1d9b08fc134b0343c7e67b4a4b42feb52df6ca295f325ef8";

/// The committed pin: this version's SHA-256 per platform, one line each,
/// so a shell and a reviewer read it without a JSON parser. `None` when this
/// server has no builds. Python's `blocks.hooks_lock`, byte for byte.
pub fn hooks_lock(builds: &[Value], version: i64) -> Option<String> {
    let mut pins: Vec<(String, String)> = builds
        .iter()
        .filter_map(|b| {
            let target = b.get("target").and_then(Value::as_str).filter(|t| !t.is_empty())?;
            let sha = b.get("sha256").and_then(Value::as_str).filter(|h| !h.is_empty())?;
            Some((target.to_string(), sha.to_string()))
        })
        .collect();
    if pins.is_empty() {
        return None;
    }
    pins.sort();
    let mut lines = vec![
        "# Collide's native hook, pinned by setup. Commit this file.".to_string(),
        "# A new machine downloads exactly the build listed for its platform and refuses".to_string(),
        "# any file whose SHA-256 differs. Updates after that must be signed by the key below.".to_string(),
        format!("version {version}"),
        format!("key {HOOK_SIGNING_KEY}"),
    ];
    lines.extend(pins.into_iter().map(|(target, sha)| format!("{target} {sha}")));
    Some(lines.join("\n") + "\n")
}
pub const PRECOMMIT_HOOK_FILE: &str = ".collide/githooks/pre-commit";
pub const CONFIG_FILE: &str = ".collide/config.json";
pub const CREDENTIALS_FILE: &str = "~/.collide/credentials.json";
/// The native binary is preferred wherever it exists — same logic compiled,
/// ~2ms to start against Python's ~33ms. Absent, everything falls through
/// to the committed Python artifact.
pub const BIN_FILE: &str = ".collide/bin/collide-hook";

// ------------------------------------------------------ hook shell commands
//
// These are module-level constants on the Python side (computed once from
// HOOK_FILE/GATE_HOOK_FILE/BIN_FILE, never from a function argument), so
// their resolved text is embedded verbatim rather than rebuilt — see the
// module doc.

/// PostToolUse report hook command (`_REPORT_HOOK_COMMAND`).
const REPORT_HOOK_COMMAND: &str = include_str!("hook_report_command.txt");
/// PreToolUse gate hook command (`_GATE_HOOK_COMMAND`).
const GATE_HOOK_COMMAND: &str = include_str!("hook_gate_command.txt");
/// SessionStart bootstrap command (`_BOOTSTRAP_COMMAND`).
const BOOTSTRAP_COMMAND: &str = include_str!("hook_bootstrap_command.txt");
/// The committed git pre-commit shim (`precommit_hook_shim()`).
const PRECOMMIT_HOOK_SHIM: &str = include_str!("hook_precommit_shim.txt");
/// `_NATIVE_INSTALL_TEMPLATE`, `__BASE__` not yet substituted.
const NATIVE_INSTALL_TEMPLATE: &str = include_str!("hook_native_install_template.txt");

pub fn precommit_hook_shim() -> &'static str {
    PRECOMMIT_HOOK_SHIM
}

/// A client hook's exact source, served as an installable artifact so
/// nothing has to be pip-installed on the agent's machine. `include_str!`
/// stands in for Python's `importlib.resources` package-data read: both
/// read the same file on disk (`client/src/collide_client/*.py`).
#[cfg(feature = "cloud")]
pub fn hook_script_source() -> &'static str {
    include_str!("../../client/src/collide_client/report_hook.py")
}

#[cfg(feature = "cloud")]
pub fn gate_hook_source() -> &'static str {
    include_str!("../../client/src/collide_client/gate_hook.py")
}

#[cfg(feature = "cloud")]
pub fn precommit_source() -> &'static str {
    include_str!("../../client/src/collide_client/pre_commit.py")
}

// The free version sets no repo up with the per-repo Python hooks: one
// install covers the machine.
#[cfg(not(feature = "cloud"))]
pub fn hook_script_source() -> &'static str {
    ""
}

#[cfg(not(feature = "cloud"))]
pub fn gate_hook_source() -> &'static str {
    ""
}

#[cfg(not(feature = "cloud"))]
pub fn precommit_source() -> &'static str {
    ""
}

/// The POSIX installer the server hands out at `/artifacts/hooks/install.sh`.
pub fn native_hook_install_script(base_url: &str) -> String {
    NATIVE_INSTALL_TEMPLATE.replace("__BASE__", base_url)
}

/// Codex `.codex/hooks.json` command builder (`_codex_hook_command`). Unlike
/// the Claude Code commands above, Codex sets no `CLAUDE_PROJECT_DIR`, so
/// this one genuinely depends on `hook_file`/`fallback`/`propagate` and is
/// real logic rather than embedded text.
fn codex_hook_command(hook_file: &str, fallback: &str, propagate: bool, harness: &str) -> String {
    let tail = if propagate { "" } else { " 2>/dev/null || true" };
    let subcommand = if propagate { "gate" } else { "report" };
    // Claude Code is the canonical dialect and takes no flag, so every
    // settings.json already committed keeps working byte for byte
    let flag = if harness == "claude" { String::new() } else { format!(" --harness {harness}") };
    let branch = if propagate {
        format!("if [ -n \"$b\" ]; then exec \"$b\" {subcommand}{flag}; fi; ")
    } else {
        format!("if [ -n \"$b\" ]; then \"$b\" {subcommand}{flag} 2>/dev/null || true; exit 0; fi; ")
    };
    format!(
        "d=\"${{CLAUDE_PROJECT_DIR:-$(git rev-parse --show-toplevel 2>/dev/null || echo .)}}\"; \
b=\"$d/{BIN_FILE}\"; [ -x \"$b\" ] || b=\"$(command -v collide-hook 2>/dev/null)\"; {branch}\
f=\"$d/{hook_file}\"; p=\"\"; for c in python3 python py; do command -v \"$c\" >/dev/null 2>&1 || continue; \"$c\" -c \"\" >/dev/null 2>&1 && {{ p=\"$c\"; break; }}; done; \
if [ -f \"$f\" ] && [ -n \"$p\" ]; then \"$p\" \"$f\"{flag}{tail}; else {fallback}{flag} 2>/dev/null || true; fi"
    )
}

// --------------------------------------------------------------- json blobs

/// Committable per-repo hook config (no secrets; the token lives in each
/// user's `~/.collide/credentials.json`).
pub fn collide_config_json(server_url: &str, repo_id: &str, workspace: &str) -> Value {
    let mut config = Map::new();
    config.insert("server_url".into(), json!(server_url.trim_end_matches('/')));
    config.insert("repo_id".into(), json!(repo_id));
    if !workspace.is_empty() {
        config.insert("workspace".into(), json!(workspace));
    }
    // the native hook parses on the machine and sends the structure the
    // server keeps, never the file (the Python fallback still sends files)
    config.insert("local_parse".into(), json!(true));
    Value::Object(config)
}

/// PostToolUse blocks: every Edit/Write auto-reports, every Read/Grep/Glob
/// posts presence. All modes.
pub fn report_hooks() -> Value {
    let hook = json!({"type": "command", "command": REPORT_HOOK_COMMAND, "timeout": 5});
    json!({
        "PostToolUse": [
            {"matcher": "Edit|Write|MultiEdit|NotebookEdit", "hooks": [hook.clone()]},
            {"matcher": "Read|Grep|Glob|Bash", "hooks": [hook.clone()]},
        ],
        // a failed call sends no PostToolUse: without this, a session whose
        // commands failed showed as no agent running
        "PostToolUseFailure": [
            {"matcher": "Edit|Write|MultiEdit|NotebookEdit|Read|Grep|Glob|Bash", "hooks": [hook.clone()]},
        ],
        "Stop": [{"hooks": [hook.clone()]}],
        // the session ended: the agent leaves the Now panel the moment it is
        // gone, instead of an hour later when silence is taken for absence
        "SessionEnd": [{"hooks": [hook.clone()]}],
        // a batch of writes landed: the repo's check runs detached, its
        // verdict rides the next event
        "PostToolBatch": [{"hooks": [{"type": "command", "command": REPORT_HOOK_COMMAND, "timeout": 10}]}],
        // the task is known: the briefing narrows to what the prompt names
        "UserPromptSubmit": [{"hooks": [{"type": "command", "command": REPORT_HOOK_COMMAND, "timeout": 10}]}],
        // the agent just wrote these very hooks into settings.json, and this
        // firing proves they loaded. Without it the setup nag clears only on
        // the first file WRITE, so a session that installs the hooks and then
        // only reads keeps being told to install them.
        "ConfigChange": [{"matcher": "project_settings|local_settings|user_settings",
                          "hooks": [{"type": "command", "command": REPORT_HOOK_COMMAND, "timeout": 5}]}],
    })
}

/// Claude Code hook blocks. Report hook ships in every mode; the gate only
/// in enforce; SessionStart injects the bootstrap/self-install check.
pub fn hooks_json(server_url: &str, mode: &str) -> Value {
    let mut hooks = report_hooks();
    let map = hooks.as_object_mut().expect("report_hooks() returns an object");
    // the reporter on SessionStart indexes the tracked tree into the map
    // once, then only what changed — a few hundred modules in a few calls
    map.insert(
        "SessionStart".into(),
        json!([{"hooks": [
            {"type": "command", "command": BOOTSTRAP_COMMAND, "timeout": 15},
            {"type": "command", "command": REPORT_HOOK_COMMAND, "timeout": 30},
        ]}]),
    );
    if mode == "enforce" {
        map.insert(
            "PreToolUse".into(),
            json!([{
                "matcher": "Edit|Write|MultiEdit|Bash",
                "hooks": [{"type": "command", "command": GATE_HOOK_COMMAND, "timeout": 5}],
            }]),
        );
    }
    json!({
        "hooks": hooks,
        "server_url": server_url,
    })
}

/// Codex `.codex/hooks.json`. Same matcher+hooks shape; `apply_patch` is
/// Codex's file-edit tool. The PreToolUse gate ships only in enforce mode.
pub fn codex_hooks_json(mode: &str) -> Value {
    let report = json!({
        "type": "command",
        "command": codex_hook_command(HOOK_FILE, "collide-report-hook", false, "codex"),
        "timeout": 5,
    });
    let mut hooks = Map::new();
    hooks.insert(
        "PostToolUse".into(),
        json!([
            {"matcher": "^(apply_patch|Edit|Write|MultiEdit)$", "hooks": [report.clone()]},
            {"matcher": "^(Read|Grep|Glob|Bash|shell)$", "hooks": [report.clone()]},
        ]),
    );
    // the reporter on SessionStart indexes the tracked tree into the map
    // once, then only what changed (inert on a Codex that does not fire it)
    let mut index = report.clone();
    index["timeout"] = json!(30);
    hooks.insert("SessionStart".into(), json!([{"hooks": [index]}]));
    // the task is known: the briefing narrows to what the prompt names
    let mut briefing = report.clone();
    briefing["timeout"] = json!(10);
    hooks.insert("UserPromptSubmit".into(), json!([{"hooks": [briefing]}]));
    // the session ended (Codex fires it on close and after 30 idle minutes):
    // the agent leaves the Now panel the moment it is gone
    hooks.insert("SessionEnd".into(), json!([{"hooks": [report]}]));
    if mode == "enforce" {
        let gate = json!({
            "type": "command",
            "command": codex_hook_command(GATE_HOOK_FILE, "collide-gate-hook", true, "codex"),
            "timeout": 5,
        });
        hooks.insert(
            "PreToolUse".into(),
            json!([{"matcher": "^(apply_patch|Edit|Write|MultiEdit|shell)$", "hooks": [gate]}]),
        );
    }
    json!({"hooks": Value::Object(hooks)})
}

/// Cursor `.cursor/hooks.json`. Cursor names its events in camelCase and
/// reads a JSON decision on stdout rather than an exit code, so the hooks are
/// invoked with `--harness cursor` and translate at both edges; the scripts
/// themselves are the same committed artifacts every other harness runs.
///
/// Five of Collide's seven events have a native home here. There is no
/// batch boundary, so the repo's own check is spawned from `postToolUse` and
/// its verdict rides the next tool result rather than the end of a write
/// batch.
pub fn cursor_hooks_json(mode: &str) -> Value {
    let report = codex_hook_command(HOOK_FILE, "collide-report-hook", false, "cursor");
    let mut hooks = Map::new();
    // the tracked tree joins the map, then the repo briefing prints
    hooks.insert("sessionStart".into(), json!([{"command": report, "timeout": 30}]));
    // the conversation ended: the agent leaves the Now panel at once
    hooks.insert("sessionEnd".into(), json!([{"command": report, "timeout": 5}]));
    // the task is known: the briefing narrows to what the prompt names
    hooks.insert("beforeSubmitPrompt".into(), json!([{"command": report, "timeout": 10}]));
    // every write reported, every read placed, notes ride the tool result
    hooks.insert(
        "postToolUse".into(),
        json!([{"matcher": "^(Write|Edit|MultiEdit|Delete|Read|Glob|Grep|Shell)$",
                "command": report, "timeout": 5}]),
    );
    // the turn ended: a usage limit is the team's business
    hooks.insert("stop".into(), json!([{"command": report, "timeout": 5}]));
    if mode == "enforce" {
        hooks.insert(
            "preToolUse".into(),
            json!([{"matcher": "^(Write|Edit|MultiEdit|Delete|Shell)$",
                    "command": codex_hook_command(GATE_HOOK_FILE, "collide-gate-hook", true, "cursor"),
                    "timeout": 5}]),
        );
    }
    json!({"version": 1, "hooks": Value::Object(hooks)})
}

/// Merge target for the repo's `.claude/settings.json`. Note: always builds
/// its hooks with `server_url=""` — matching Python's `hooks_json(mode=mode)`
/// call, which never passes `server_url` here — because only the `hooks`
/// sub-object is used; the (unused) `server_url` field of that intermediate
/// result is discarded either way.
pub fn claude_settings_json(mode: &str) -> Value {
    let inner = hooks_json("", mode);
    json!({
        "permissions": {"allow": ["mcp__collide"]},
        "enabledMcpjsonServers": ["collide"],
        "hooks": inner.get("hooks").cloned().unwrap_or_else(|| json!({})),
    })
}

/// Which settings file each harness installs the hooks into.
pub const SETTINGS_FILES: &[(&str, &str)] = &[
    ("claude", ".claude/settings.json"),
    ("codex", CODEX_HOOKS_FILE),
    ("cursor", CURSOR_HOOKS_FILE),
];

const SETTINGS_MODES: [&str; 2] = ["enforce", "advisory"];

/// A shell command that runs one of Collide's hooks, in any dialect.
pub(crate) fn is_collide_command(text: &str) -> bool {
    text.contains("collide")
        && (text.contains(HOOK_FILE)
            || text.contains(GATE_HOOK_FILE)
            || text.contains(BIN_FILE)
            || text.contains("collide-hook")
            || text.contains("collide-report-hook")
            || text.contains("collide-gate-hook"))
}

/// Walks the structure instead of knowing each dialect's shape, so one
/// traversal covers Claude Code, Codex and Cursor alike — and a developer's
/// own unrelated hooks never enter the digest, so merging Collide into an
/// existing settings file does not read as drift. Each command is tagged
/// with the EVENT it is wired under — the nearest enclosing key that is not
/// the dialect's own "hooks"/"command" plumbing — so wiring the same script
/// to one more event changes the digest, which is the drift this
/// fingerprint exists to catch. Python's `_collide_commands`.
fn walk_commands(node: &Value, event: &str, found: &mut std::collections::BTreeSet<String>) {
    match node {
        Value::Object(map) => {
            for (key, value) in map {
                let under = if key == "hooks" || key == "command" { event } else { key.as_str() };
                walk_commands(value, under, found);
            }
        }
        Value::Array(items) => {
            for value in items {
                walk_commands(value, event, found);
            }
        }
        Value::String(text) if is_collide_command(text) => {
            found.insert(format!("{event}\t{text}"));
        }
        _ => {}
    }
}

/// Python's `blocks.settings_digest`: a fingerprint of the Collide hooks a
/// settings blob installs, or `""` for none.
///
/// `HOOK_ARTIFACT_VERSION` covers the committed SCRIPTS. This covers the
/// settings block that decides whether those scripts are ever reached: which
/// events are wired at all, and whether the native-binary branch exists. The
/// two drift independently, and a repo current on one can be far behind on
/// the other — invisible before this, because only the script carried a
/// version.
pub fn settings_digest(blob: &Value) -> String {
    let mut found = std::collections::BTreeSet::new();
    walk_commands(blob, "", &mut found);
    if found.is_empty() {
        return String::new();
    }
    let joined = found.into_iter().collect::<Vec<_>>().join("\n");
    use sha2::{Digest, Sha256};
    let hex = format!("{:x}", Sha256::digest(joined.as_bytes()));
    hex[..12].to_string()
}

/// Python's `blocks.current_settings_digests`: every digest a correctly
/// installed settings file could have right now, across the harnesses and
/// modes Collide generates. Membership is the whole check.
pub fn current_settings_digests() -> std::collections::BTreeSet<String> {
    let mut out = std::collections::BTreeSet::new();
    for mode in SETTINGS_MODES {
        out.insert(settings_digest(&claude_settings_json(mode)));
        out.insert(settings_digest(&codex_hooks_json(mode)));
        out.insert(settings_digest(&cursor_hooks_json(mode)));
    }
    out.remove("");
    out
}

/// Merge target for the repo's `.mcp.json`.
pub fn mcp_json(server_url: &str, mcp_url: &str) -> Value {
    json!({"mcpServers": {"collide": {"type": "http", "url": mcp_endpoint(server_url, mcp_url)}}})
}

/// Return `(new_content, markers_were_present)`. Only the region between
/// the collide markers is replaced; everything outside is byte-identical.
/// Absent markers -> the wrapped block is appended.
pub fn sync_agents_content(file_content: &str, repo_id: &str) -> (String, bool) {
    let block = canonical_block(repo_id);
    let start_idx = file_content.find(START_MARKER);
    let end_idx = start_idx.and_then(|start| {
        file_content[start + START_MARKER.len()..]
            .find(END_MARKER)
            .map(|rel| start + START_MARKER.len() + rel)
    });

    match (start_idx, end_idx) {
        (Some(start), Some(end)) => {
            let prefix = &file_content[..start];
            let suffix = &file_content[end + END_MARKER.len()..];
            (format!("{prefix}{block}{suffix}"), true)
        }
        _ => {
            let mut prefix = file_content.to_string();
            if !prefix.is_empty() && !prefix.ends_with('\n') {
                prefix.push('\n');
            }
            let sep = if prefix.is_empty() { "" } else { "\n" };
            (format!("{prefix}{sep}{block}\n"), false)
        }
    }
}

/// Python's `json.dumps(value, indent=2) + "\n"`, for artifact content that
/// is genuinely written to a file (`.collide/config.json`,
/// `~/.collide/credentials.json`, `.mcp.json`, `.codex/hooks.json`) rather
/// than an ephemeral protocol reply — so it is worth matching Python's
/// formatting exactly rather than any valid JSON rendering. `serde_json`'s
/// pretty-printer produces the identical 2-space/`": "`/no-trailing-comma
/// shape, and this crate's `Map` preserves insertion order (`serde_json`
/// pulls in `indexmap` here), so key order matches too as long as the
/// `Value` was built in the same order as the Python dict literal.
pub(crate) fn dumps_with_newline(value: &Value) -> String {
    format!("{}\n", serde_json::to_string_pretty(value).unwrap_or_else(|_| "{}".into()))
}

// -------------------------------------------------------------- setup() tool

/// Python's `service.setup(repo_id, mode)` — pure, no store access.
/// `setup_notes`/`enforce_notes` text is authored guidance shown to an
/// agent, copied verbatim.
pub fn setup(repo_id: &str, mode: &str, public_url: &str, mcp_url: &str) -> Value {
    let mode = if mode == "advisory" || mode == "enforce" { mode } else { "enforce" };
    let mut result = Map::new();
    result.insert("mode".into(), json!(mode));
    result.insert("agents_md_block".into(), json!(canonical_block(repo_id)));
    result.insert("markers".into(), json!({"start": START_MARKER, "end": END_MARKER}));
    result.insert("apply_with".into(), json!("sync_agents_block"));
    result.insert("claude_settings".into(), claude_settings_json(mode));
    result.insert("mcp_json".into(), mcp_json(public_url, mcp_url));
    result.insert("setup_notes".into(), json!([
        "Merge claude_settings into the repo's .claude/settings.json (create it if absent) and \
commit: Claude Code then auto-allows every collide tool call instead of prompting each \
time. The allow entry is scoped to mcp__collide only.",
        "Merge mcp_json into the repo's .mcp.json and commit so every teammate's client discovers \
the server; each user still authenticates through OAuth as themselves.",
        "claude_settings wires the hooks that report every Edit/Write, brief the session and \
run the repo's check — no model in the loop. They are the committed scripts in repo_files and \
need nothing installed: no package, nothing on PATH, no environment variables. They read \
.collide/config.json and the per-machine credential, and they fail open, so a machine without \
one is silent rather than broken.",
    ]));
    result.insert("hooks".into(), hooks_json(public_url, mode));
    if mode == "enforce" {
        result.insert("enforce_notes".into(), json!([
            "Enforce is the default: a PreToolUse gate calls check_collisions before every \
Edit/Write and BLOCKS the write on a confidence-certain collision, so the model \
never has to remember to check. Pass mode='advisory' to ship reporting without the gate.",
            "The gate ships as a committed repo artifact (.collide/gate_hook.py) alongside the \
report hook — no pip, no PATH; it reads .collide/config.json like the report hook.",
            "The hook fails open: any error, timeout, missing config, or non-200 allows the write.",
            "Enforce works on Claude Code, Codex, Cursor and Hermes: each has a pre-tool hook \
that can refuse a write, and the committed gate answers in whichever shape that harness \
reads. Anything else runs advisory, with the git pre-commit hook as the floor.",
        ]));
    }
    Value::Object(result)
}

// ---------------------------------------------------- sync_agents_block() tool

/// Python's `service.sync_agents_block`. Text transform plus the ticker
/// flip: calling this IS the setup act, so the scope is marked applied at
/// the current version. `verified=true` when the content was already
/// canonical (the one physical check, performed once).
pub fn sync_agents_block(store: &Store, scope: &str, user_id: &str, repo_id: &str, file_content: &str) -> Value {
    let (content, markers_found) = sync_agents_content(file_content, repo_id);
    let changed = content != file_content;
    let stamp = now();
    let state = json!({
        "applied_version": BLOCK_VERSION,
        "applied_by": user_id,
        "verified": !changed,
        "ts": stamp,
    });
    let _ = store.kv_put("setup_state", scope, &state, stamp);
    let _ = store.ledger_append(
        scope,
        "setup_applied",
        &json!({"user": user_id, "version": BLOCK_VERSION, "verified": !changed}),
        stamp,
    );
    json!({"content": content, "markers_found": markers_found, "changed": changed})
}

// --------------------------------------------------- hook credential minting

/// Mirrors `auth::token_key` (SHA256 hex of the raw token — tokens are
/// stored hashed so a DB leak never leaks a usable credential). Duplicated
/// rather than made `pub` on `auth.rs`: that module is being actively
/// extended by a concurrent port (OAuth 2.1 flow), and this is three lines
/// of the same standard algorithm, not a design decision to share.
fn token_key(token: &str) -> String {
    use sha2::{Digest, Sha256};
    let mut hasher = Sha256::new();
    hasher.update(token.as_bytes());
    format!("{:x}", hasher.finalize())
}

/// `n` bytes of OS-sourced randomness with no extra dependency, built the
/// same way `compat::new_id` gets its uniqueness: `RandomState::new()`
/// draws fresh SipHash keys from the OS RNG on every construction (not
/// cached), so hashing a counter under a freshly-constructed `RandomState`
/// each round is an OS-randomness extractor, not a clock-seeded PRNG.
pub(crate) fn random_bytes(n: usize) -> Vec<u8> {
    use std::collections::hash_map::RandomState;
    use std::hash::{BuildHasher, Hasher};
    let mut bytes = Vec::with_capacity(n + 8);
    let mut counter: u64 = 0;
    while bytes.len() < n {
        let mut hasher = RandomState::new().build_hasher();
        hasher.write_u64(counter);
        counter += 1;
        bytes.extend_from_slice(&hasher.finish().to_le_bytes());
    }
    bytes.truncate(n);
    bytes
}

/// Python's `secrets.token_urlsafe(32)`, prefixed like `ACCESS_TOKEN_PREFIX`
/// in `auth.py`. The exact character alphabet does not need to match
/// Python's generator byte-for-byte (this is fresh secret material, never
/// compared across servers) — only the bucket/record shape does.
fn mint_raw_token() -> String {
    use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine as _};
    format!("{}{}", crate::auth::ACCESS_TOKEN_PREFIX, URL_SAFE_NO_PAD.encode(random_bytes(32)))
}

/// The identity a minted hook credential is bound to. Field names spell out
/// exactly which Python variable each comes from, since `AuthUser`/`Principal`
/// are still being ported (see the module doc's scope boundary).
pub struct HookIdentity<'a> {
    /// `auth.uid` — becomes the token record's `"uid"`.
    pub auth_uid: &'a str,
    /// `principal.email`.
    pub email: &'a str,
    /// `principal.name`.
    pub name: &'a str,
    /// `workspace_for(auth, repo_id)` — the repo's ROUTED workspace, which
    /// may differ from the caller's own default workspace.
    pub workspace: &'a str,
}

/// A fresh 90-day workspace-bound hook token, shaped as the
/// `~/.collide/credentials.json` artifact, and written into `TOKEN_BUCKET`
/// in the shape `auth::principal_for_bearer` already reads (`kind`,
/// `expires`, `uid`, `email`, `workspace`). `client_id` distinguishes
/// `setup`/`install_hooks` (`"collide-hook"`) from `connect_agents`
/// (`"collide-connect"`), matching Python.
pub fn mint_hook_credential(store: &Store, identity: &HookIdentity, client_id: &str, public_url: &str) -> Value {
    let created = now();
    let token = mint_raw_token();
    let record = json!({
        "uid": identity.auth_uid, "email": identity.email, "name": identity.name,
        "workspace": identity.workspace, "client_id": client_id,
        "created": created, "kind": "access", "expires": created + 90.0 * 86_400.0,
    });
    let _ = store.kv_put(crate::auth::TOKEN_BUCKET, &token_key(&token), &record, created);

    let mut credentials = Map::new();
    credentials.insert("token".into(), json!(token));
    let server_url = public_url.trim_end_matches('/');
    if !server_url.is_empty() {
        credentials.insert(server_url.to_string(), json!(token));
        credentials.insert(format!("{server_url}#{}", identity.workspace), json!(token));
    }
    Value::Object(credentials)
}

const HOOKS_INSTALLED_TTL_S: f64 = 7.0 * 86_400.0;

/// `setup`/`install_hooks`/`connect_agents` minted a hook credential for
/// this user on this scope. From now until the first hook-path report, an
/// edit that still arrives by hand is evidence the hooks did not load
/// (`restart_notice`, in `envelope.rs`, reads this same stamp). Never
/// overwrites an earlier one: the install time is what the notice reports.
pub fn mark_hooks_installed(store: &Store, scope: &str, user_id: &str) {
    let key = format!("hooksinstalled:{scope}:{user_id}");
    if store.eph_get(&key).is_none() {
        let _ = store.eph_set(&key, &json!({"ts": now()}), Some(HOOKS_INSTALLED_TTL_S));
    }
}

fn push_note(map: &mut Map<String, Value>, note: &str) {
    map.entry("setup_notes")
        .or_insert_with(|| json!([]))
        .as_array_mut()
        .expect("setup_notes is always the array this function created")
        .push(json!(note));
}

// ------------------------------------------------------- full tool responses

/// Everything `setup_tool_response` / `install_hooks_response` /
/// `connect_agents_response` need, already resolved by the caller — see the
/// module doc's scope boundary. The MCP layer still owns auth, workspace
/// routing, and (for install_hooks/connect_agents) the read-only refusal.
pub struct ArtifactRequest<'a> {
    pub repo_id: &'a str,
    pub public_url: &'a str,
    pub mcp_url: &'a str,
    /// `workspace_for(auth, repo_id)`.
    pub workspace: &'a str,
    /// `auth.uid`.
    pub auth_uid: &'a str,
    /// `principal.email`.
    pub email: &'a str,
    /// `principal.name`.
    pub name: &'a str,
    /// `auth.user_id` — the ledger actor label (`scope_of`'s caller).
    pub user_id: &'a str,
    /// `scope_of(auth, repo_id)`.
    pub scope: &'a str,
    /// the calling agent's self-identification (`agent_of(ctx)`), for the
    /// ledger row `install_hooks`/`connect_agents` record.
    pub agent: &'a str,
}

impl ArtifactRequest<'_> {
    pub(crate) fn identity(&self) -> HookIdentity<'_> {
        HookIdentity { auth_uid: self.auth_uid, email: self.email, name: self.name, workspace: self.workspace }
    }
}

/// Python's `setup` MCP tool: `service.setup()` plus `repo_files` (always)
/// and `user_files` (only when `can_write` — a read-only member gets
/// advisory-mode artifacts with no credential). The optional `native_hook`
/// block Python adds when compiled hook builds exist is not reproduced: no
/// `artifacts.rs` registry has been ported yet, so this always takes the
/// same path Python takes when zero builds are available (silently omit
/// the field) — never a wrong claim, just an honest "not yet checked".
pub fn setup_tool_response(store: &Store, mode: &str, can_write: bool, req: &ArtifactRequest) -> Value {
    // a workspace on Free gets the free version: installed once for every
    // repo on the machine, all of it local (machines.rs)
    if can_write && mode != "files" {
        if let Some(free) = crate::machines::offer_free(store, req.public_url, req.workspace, req.auth_uid, req.email, req.name) {
            return free;
        }
    }
    // a server with a build to pin answers with one command (setupone.rs)
    if let Some(quick) = crate::setupone::offer(store, mode, can_write, req) {
        return quick;
    }
    // "files" only skips the command; the files it returns are enforce mode's
    let mode = if mode == "files" { "enforce" } else { mode };
    let mut result = setup(req.repo_id, mode, req.public_url, req.mcp_url);
    let map = result.as_object_mut().expect("setup() returns an object");

    map.insert("repo_files".into(), json!({
        HOOK_FILE: hook_script_source(),
        GATE_HOOK_FILE: gate_hook_source(),
        CONFIG_FILE: dumps_with_newline(&collide_config_json(req.public_url, req.repo_id, req.workspace)),
        NATIVE_INSTALL_FILE: native_hook_install_script(req.public_url),
    }));
    push_note(map, "repo_files: write into the repo and COMMIT them (the hook scripts + a \
no-secrets config) — every teammate then runs the current hooks with zero installation.");

    // the compiled hooks, offered only when this server has a build to serve:
    // a suggestion to install something that 404s would be worse than silence
    let builds = crate::artifacts::available();
    if let Some(lock) = hooks_lock(&builds, crate::envelope::HOOK_ARTIFACT_VERSION) {
        if let Some(files) = map.get_mut("repo_files").and_then(Value::as_object_mut) {
            files.insert(HOOKS_LOCK_FILE.into(), json!(lock));
        }
    }
    if !builds.is_empty() {
        let index = if req.public_url.is_empty() {
            "/artifacts/hooks".to_string()
        } else {
            format!("{}/artifacts/hooks", req.public_url)
        };
        map.insert("native_hook".into(), json!({
            "why": "the same gate/report/pre-commit/watch logic compiled — about 17x \
faster to start, on something that runs for every tool call",
            "install": format!("sh {NATIVE_INSTALL_FILE}"),
            "index": index,
            "targets": builds.iter().map(|b| b.get("target").cloned().unwrap_or(Value::Null))
                .collect::<Vec<_>>(),
            "optional": true,
        }));
        push_note(map, &format!(
            "native_hook (optional): run `sh {NATIVE_INSTALL_FILE}` once per machine to \
install the compiled hooks. It verifies the digest, installs to .collide/bin/ (gitignore \
that), and changes nothing if this server has no build for the platform — the Python \
hooks keep working either way."));
    }

    if can_write {
        let credentials = mint_hook_credential(store, &req.identity(), "collide-hook", req.public_url);
        mark_hooks_installed(store, req.scope, req.user_id);
        map.insert("user_files".into(), json!({CREDENTIALS_FILE: dumps_with_newline(&credentials)}));
        push_note(map, "user_files: install MERGING, not overwriting — save the JSON content to a \
temp file and run `python .collide/report_hook.py --add-credentials <file>` \
(merges into ~/.collide/credentials.json; other workspaces' credentials \
survive). Per-user, NEVER committed.");
    }
    push_note(map, "Hooks: Claude Code hot-reloads .claude/settings.json within seconds, so the hooks \
just installed normally fire in THIS session already — no restart by default. Keep \
reporting your next write with report_edit: if that response carries \
restart_required, this session missed the change and you must tell the human to \
restart. A NEW .mcp.json entry is different: teammates need a fresh session to \
discover the server (you are already connected to it).");
    result
}

/// Python's `install_hooks` MCP tool. Errs with the exact read-only message
/// Python raises (`PermissionError`) when `can_write` is false — the caller
/// (MCP dispatch) is expected to surface this as a refusal, same as Python.
pub fn install_hooks_response(store: &Store, can_write: bool, req: &ArtifactRequest) -> Result<Value, String> {
    if !can_write {
        return Err("read-only access: the hook reports edits; ask the workspace owner for write access".into());
    }
    let credentials = mint_hook_credential(store, &req.identity(), "collide-hook", req.public_url);
    let _ = store.ledger_append(
        req.scope, "hooks_installed", &json!({"user": req.user_id, "agent": req.agent}), now());
    mark_hooks_installed(store, req.scope, req.user_id);
    Ok(json!({
        "repo_files": {
            HOOK_FILE: hook_script_source(),
            GATE_HOOK_FILE: gate_hook_source(),
            CONFIG_FILE: dumps_with_newline(&collide_config_json(req.public_url, req.repo_id, req.workspace)),
        },
        "user_files": {CREDENTIALS_FILE: dumps_with_newline(&credentials)},
        "claude_settings": claude_settings_json("enforce"),
        "token_expires_in_days": 90,
        "notes": [
            "Write repo_files into the repo (create the .collide directory) and commit them — \
every teammate then has the hook with zero installation.",
            "Write user_files under the user's HOME directory (create ~/.collide if needed). \
NEVER commit the credentials file; it is this user's identity.",
            "Merge claude_settings into the repo's .claude/settings.json if setup has not \
already been applied.",
            "The token is workspace-bound to the caller and expires in 90 days; re-run \
install_hooks to mint a fresh one.",
            "Hooks hard-fail open within 500ms; they can never disturb or slow real work.",
            "Hooks: Claude Code hot-reloads .claude/settings.json within seconds, so the hooks \
just installed normally fire in THIS session already — no restart by default. Keep \
reporting your next write with report_edit: if that response carries \
restart_required, this session missed the change and you must tell the human to \
restart. A NEW .mcp.json entry is different: teammates need a fresh session to \
discover the server (you are already connected to it).",
        ],
    }))
}

/// Python's `connect_agents` MCP tool: the one-call multi-agent installer.
/// `repo_files` order matches Python's dict-merge exactly: `agent_rules_files`
/// (5 entries) then `agent_mcp_files` (2 entries) then the four
/// Claude/Codex/pre-commit artifacts assigned after.
pub fn connect_agents_response(store: &Store, can_write: bool, req: &ArtifactRequest) -> Result<Value, String> {
    if !can_write {
        return Err(
            "read-only access: connecting agents mints a reporting token; ask the owner for write access".into(),
        );
    }
    let credentials = mint_hook_credential(store, &req.identity(), "collide-connect", req.public_url);
    let _ = store.ledger_append(
        req.scope, "hooks_installed", &json!({"user": req.user_id, "agent": req.agent}), now());
    mark_hooks_installed(store, req.scope, req.user_id);

    let mut repo_files = Map::new();
    if let Value::Object(rules) = agent_rules_files(req.repo_id) {
        repo_files.extend(rules);
    }
    if let Value::Object(mcp_files) = agent_mcp_files(req.public_url, req.mcp_url) {
        repo_files.extend(mcp_files);
    }
    repo_files.insert(HOOK_FILE.into(), json!(hook_script_source()));
    repo_files.insert(GATE_HOOK_FILE.into(), json!(gate_hook_source()));
    repo_files.insert(
        CONFIG_FILE.into(),
        json!(dumps_with_newline(&collide_config_json(req.public_url, req.repo_id, req.workspace))),
    );
    repo_files.insert(PRECOMMIT_SCRIPT_FILE.into(), json!(precommit_source()));
    repo_files.insert(PRECOMMIT_HOOK_FILE.into(), json!(precommit_hook_shim()));
    if let Some(lock) = hooks_lock(&crate::artifacts::available(), crate::envelope::HOOK_ARTIFACT_VERSION) {
        repo_files.insert(HOOKS_LOCK_FILE.into(), json!(lock));
    }
    // the same committed scripts, each harness's own config file: Codex and
    // Cursor both get real per-edit blocking, not just advisory
    repo_files.insert(CODEX_HOOKS_FILE.into(), json!(dumps_with_newline(&codex_hooks_json("enforce"))));
    repo_files.insert(CURSOR_HOOKS_FILE.into(), json!(dumps_with_newline(&cursor_hooks_json("enforce"))));

    Ok(json!({
        "repo_files": Value::Object(repo_files),
        "user_files": {CREDENTIALS_FILE: dumps_with_newline(&credentials)},
        "claude_settings": claude_settings_json("enforce"),
        "snippets": agent_snippets(req.public_url, req.repo_id, req.mcp_url),
        "token_expires_in_days": 90,
        "notes": [
            "MERGE the marker-wrapped files (AGENTS.md, .windsurfrules, .github/copilot-instructions.md) \
so you never clobber existing instructions — use sync_agents_block, or paste the block \
between its <!-- collide:start/end --> markers. Write the dedicated files \
(.cursor/rules/collide.mdc, .clinerules/collide.md, .mcp.json, .cursor/mcp.json) as-is. \
Commit all of them so every teammate's agent inherits the protocol.",
            "Write user_files under HOME (~/.collide); NEVER commit the credentials file — it is this \
user's identity.",
            "Merge claude_settings into .claude/settings.json for the enforce-mode gate (Claude Code).",
            "Enable the git pre-commit gate — the ONE blocking chokepoint that works for every agent \
and humans — with: git config core.hooksPath .collide/githooks && chmod +x \
.collide/githooks/pre-commit. It blocks a commit that lands on a certain in-flight \
collision (override a false positive with git commit --no-verify).",
            "snippets.codex and snippets.cline_windsurf are user-global MCP config, not repo files.",
            "snippets.watcher is the enforcement floor for any agent without hooks: it reports every \
edit from disk (source: disk). Run it with the token from ~/.collide/credentials.json.",
            "The server's own MCP instructions push the protocol to any connected MCP agent, so tools \
beyond this list are covered the moment they connect.",
        ],
    }))
}

// ------------------------------------------------------------------- tests

#[cfg(test)]
mod tests {
    use super::*;

    /// Golden values dumped by running the Python functions with the same
    /// inputs used below (`PYTHONPATH=src python3 -c '...'`, see the
    /// commit that added this file). Catches any drift in the translated
    /// logic (`hooks_json`, `codex_hooks_json`, `collide_config_json`,
    /// `mcp_json`, `agent_*`, `sync_agents_content`, `setup`) without
    /// hand-copying the shell-command strings a second time.
    fn golden() -> Value {
        serde_json::from_str(include_str!("blocks_golden.json")).expect("golden fixture is valid JSON")
    }

    #[test]
    fn versions_match_envelope() {
        assert_eq!(BLOCK_VERSION, golden()["BLOCK_VERSION"].as_i64().unwrap());
        assert_eq!(HOOK_ARTIFACT_VERSION, golden()["HOOK_ARTIFACT_VERSION"].as_i64().unwrap());
    }

    /// The settings digest is the SECOND staleness signal — the one that
    /// catches a settings block wired before a hook change, which the
    /// script's own version can never see. Both halves must agree on it or
    /// the server would call a correct install stale.
    #[test]
    fn settings_digests_match_python() {
        let g = golden();
        assert_eq!(
            settings_digest(&claude_settings_json("enforce")),
            g["settings_digest_claude_enforce"].as_str().unwrap());
        assert_eq!(
            settings_digest(&claude_settings_json("advisory")),
            g["settings_digest_claude_advisory"].as_str().unwrap());
        assert_eq!(
            settings_digest(&codex_hooks_json("enforce")),
            g["settings_digest_codex_enforce"].as_str().unwrap());
        assert_eq!(
            settings_digest(&cursor_hooks_json("enforce")),
            g["settings_digest_cursor_enforce"].as_str().unwrap());
        // somebody else's hooks are not ours: no Collide command, no digest
        let foreign = serde_json::json!({"hooks": {"PostToolUse": [{"hooks": [{"command": "echo hi"}]}]}});
        assert_eq!(settings_digest(&foreign), g["settings_digest_empty"].as_str().unwrap());
        assert_eq!(settings_digest(&foreign), "");

        let current: Vec<String> = current_settings_digests().into_iter().collect();
        let want: Vec<String> = g["current_settings_digests"].as_array().unwrap()
            .iter().map(|v| v.as_str().unwrap().to_string()).collect();
        assert_eq!(current, want);
        // every generated install must be recognised as current
        assert!(current.contains(&settings_digest(&claude_settings_json("enforce"))));
    }

    #[test]
    fn file_path_constants_match() {
        let g = golden();
        assert_eq!(HOOK_FILE, g["HOOK_FILE"].as_str().unwrap());
        assert_eq!(GATE_HOOK_FILE, g["GATE_HOOK_FILE"].as_str().unwrap());
        assert_eq!(PRECOMMIT_SCRIPT_FILE, g["PRECOMMIT_SCRIPT_FILE"].as_str().unwrap());
        assert_eq!(NATIVE_INSTALL_FILE, g["NATIVE_INSTALL_FILE"].as_str().unwrap());
        assert_eq!(PRECOMMIT_HOOK_FILE, g["PRECOMMIT_HOOK_FILE"].as_str().unwrap());
        assert_eq!(CONFIG_FILE, g["CONFIG_FILE"].as_str().unwrap());
        assert_eq!(CREDENTIALS_FILE, g["CREDENTIALS_FILE"].as_str().unwrap());
        assert_eq!(BIN_FILE, g["BIN_FILE"].as_str().unwrap());
        assert_eq!(CODEX_HOOKS_FILE, g["CODEX_HOOKS_FILE"].as_str().unwrap());
        assert_eq!(CURSOR_HOOKS_FILE, g["CURSOR_HOOKS_FILE"].as_str().unwrap());
    }

    #[test]
    fn canonical_block_and_parse_round_trip() {
        let g = golden();
        let block = canonical_block("acme/repo");
        assert_eq!(block, g["canonical_block"].as_str().unwrap());
        assert_eq!(parse_block_version(&block), Some(BLOCK_VERSION));
        assert_eq!(parse_block_version("no markers"), None);
    }

    #[test]
    fn agent_rules_files_match() {
        assert_eq!(agent_rules_files("acme/repo"), golden()["agent_rules_files"]);
    }

    #[test]
    fn agent_mcp_files_and_snippets_match() {
        let g = golden();
        assert_eq!(agent_mcp_files("https://x.test", ""), g["agent_mcp_files"]);
        assert_eq!(agent_snippets("https://x.test", "acme/repo", ""), g["agent_snippets"]);
    }

    #[test]
    fn mcp_endpoint_matches() {
        let g = golden();
        assert_eq!(mcp_endpoint("https://x.test/", ""), g["mcp_endpoint"].as_str().unwrap());
        assert_eq!(mcp_endpoint("", "https://mcp.x.test/mcp/"), g["mcp_endpoint_mcpurl"].as_str().unwrap());
        assert_eq!(mcp_endpoint("", ""), g["mcp_endpoint_default"].as_str().unwrap());
    }

    #[test]
    fn report_hooks_and_hooks_json_match() {
        let g = golden();
        assert_eq!(report_hooks(), g["report_hooks"]);
        assert_eq!(hooks_json("https://x.test", "enforce"), g["hooks_json_enforce"]);
        assert_eq!(hooks_json("https://x.test", "advisory"), g["hooks_json_advisory"]);
        assert_eq!(hooks_json("", "enforce"), g["hooks_json_noserver"]);
    }

    #[test]
    fn codex_hooks_json_matches() {
        let g = golden();
        assert_eq!(codex_hooks_json("enforce"), g["codex_hooks_json_enforce"]);
        assert_eq!(codex_hooks_json("advisory"), g["codex_hooks_json_advisory"]);
        assert_eq!(cursor_hooks_json("enforce"), g["cursor_hooks_json_enforce"]);
        assert_eq!(cursor_hooks_json("advisory"), g["cursor_hooks_json_advisory"]);
    }

    #[test]
    fn claude_settings_and_mcp_json_match() {
        let g = golden();
        assert_eq!(claude_settings_json("enforce"), g["claude_settings_json_enforce"]);
        assert_eq!(claude_settings_json("advisory"), g["claude_settings_json_advisory"]);
        assert_eq!(mcp_json("https://x.test", ""), g["mcp_json"]);
        assert_eq!(mcp_json("", "https://mcp.x.test/mcp"), g["mcp_json_mcpurl"]);
        assert_eq!(mcp_json("", ""), g["mcp_json_default"]);
    }

    #[test]
    fn collide_config_json_matches() {
        let g = golden();
        assert_eq!(
            collide_config_json("https://x.test/", "acme/repo", "ws1"),
            g["collide_config_json"]
        );
        assert_eq!(
            collide_config_json("https://x.test", "acme/repo", ""),
            g["collide_config_json_noworkspace"]
        );
    }

    #[test]
    fn native_hook_install_script_matches() {
        assert_eq!(
            native_hook_install_script("https://x.test"),
            golden()["native_hook_install_script"].as_str().unwrap()
        );
    }

    #[test]
    fn precommit_hook_shim_matches() {
        assert_eq!(precommit_hook_shim(), golden()["precommit_hook_shim"].as_str().unwrap());
    }

    #[test]
    fn sync_agents_content_matches() {
        let g = golden();
        let (content, markers) = sync_agents_content("hello world\nno markers here\n", "acme/repo");
        assert_eq!(content, g["sync_agents_content_absent"]["content"].as_str().unwrap());
        assert_eq!(markers, g["sync_agents_content_absent"]["markers_found"].as_bool().unwrap());

        let existing = format!("before\n{}\nafter\n", canonical_block("old/repo"));
        let (content, markers) = sync_agents_content(&existing, "acme/repo");
        assert_eq!(content, g["sync_agents_content_present"]["content"].as_str().unwrap());
        assert_eq!(markers, g["sync_agents_content_present"]["markers_found"].as_bool().unwrap());
    }

    #[test]
    fn setup_matches() {
        let g = golden();
        assert_eq!(setup("acme/repo", "enforce", "https://x.test", ""), g["setup_enforce"]);
        assert_eq!(setup("acme/repo", "advisory", "https://x.test", ""), g["setup_advisory"]);
        // an unrecognized mode falls back to enforce, same as Python
        assert_eq!(setup("acme/repo", "bogus", "https://x.test", ""), g["setup_enforce"]);
    }

    #[test]
    fn mint_raw_token_is_unique_and_shaped() {
        // no golden equivalent (fresh secret material every call) — just the
        // invariants a hook credential needs: prefixed, non-empty, distinct.
        let a = mint_raw_token();
        let b = mint_raw_token();
        assert!(a.starts_with(crate::auth::ACCESS_TOKEN_PREFIX));
        assert_ne!(a, b);
        assert!(a.len() > crate::auth::ACCESS_TOKEN_PREFIX.len() + 32);
    }
}
